#!/usr/bin/env bash
#Install and Configure Nginx on a server
sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" >> /var/www/html/index.html
sudo service restart nginx
