#!/usr/bin/env bash
# Configures a webserver
sudo apt update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'School' > /var/www/html/index.html
echo "404 - Not Found" > /usr/share/nginx/html/custom_404.html
sed -i "/listen 80 default_server/a add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.google.com permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default
service nginx start
