#!/usr/bin/env bash
# Installs and configures HAProxy 1.6
apt-get -y update
apt-get -y install haproxy=1.6.\*
cat >> /etc/haproxy/haproxy.cfg << EOF
backend web-backend
	balance roundrobin
	server 157311-web-01 54.172.63.43:80 check
	server 157311-web-02 54.197.86.203:80 check
frontend web-frontend
	bind *:80
	mode http
	default_backend web-backend
EOF
service haproxy restart
