#!/usr/bin/env bash
# Configures container so that Nginx is running as the nginx user.
sed -i 's/\(listen \(\[::]:\)\?\)80/\18080/g' /etc/nginx/sites-enabled/default
chmod 0644 /etc/nginx/nginx.conf
chown -R nginx:nginx /etc/nginx/
pkill apache2
sudo -u nginx service nginx restart
